### ISSUE TITLE
Gitea Bounty

### ISSUE THREAD

**Issue by Trevor-Wallis** [npease18/npease18#1]
This is the best way I could come up with contacting you. I stumbled upon a bounty ([https://app.bountysource.com/issues/92029647-feature-proposal-profile-readmes](https://app.bountysource.com/issues/92029647-feature-proposal-profile-readmes)) by accident for a Gitea feature you implemented you could try to claim.

**Comment by npease18** [comment]
Thank you very much for the information! Never knew Gitea had bounties. I put a request in. Thanks!
